POST {{url}}/public/auth
Content-Type: application/json

{
"email": "{{email}}",
"password": "{{password}}"
}

> {%
    client.global.set("auth_token", response.body.jwt);
%}

###

POST {{url}}/secured/admin/messaging
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "type": "GENERAL",
  "title": "Morgen beginnt das Fest!",
  "body": "Die letzten News bevor es losgeht findest du hier...",
  "route": "/page/2"
}

###

POST {{url}}/secured/admin/messaging/favorite
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "identifier": "harmonie-am-bachtel",
  "title": "Harmonie am Bachtel",
  "body": "In 15 Minuten spielen sie in der Zentrumshalle."
}
