ALTER TABLE verein
    MODIFY COLUMN modula BIT(1) NOT NULL DEFAULT 0;
ALTER TABLE verein
    MODIFY COLUMN modulb BIT(1) NOT NULL DEFAULT 0;
ALTER TABLE verein
    MODIFY COLUMN modulc BIT(1) NOT NULL DEFAULT 0;
ALTER TABLE verein
    MODIFY COLUMN moduld BIT(1) NOT NULL DEFAULT 0;
ALTER TABLE verein
    MODIFY COLUMN module BIT(1) NOT NULL DEFAULT 0;
ALTER TABLE verein
    MODIFY COLUMN modulf BIT(1) NOT NULL DEFAULT 0;
ALTER TABLE verein
    MODIFY COLUMN modulg BIT(1) NOT NULL DEFAULT 0;
ALTER TABLE verein
    MODIFY COLUMN modulh BIT(1) NOT NULL DEFAULT 0;

ALTER TABLE verein
    MODIFY COLUMN harmonie BIT(1) NOT NULL DEFAULT 0;
ALTER TABLE verein
    MODIFY COLUMN brass_band BIT(1) NOT NULL DEFAULT 0;
ALTER TABLE verein
    MODIFY COLUMN fanfare BIT(1) NOT NULL DEFAULT 0;
ALTER TABLE verein
    MODIFY COLUMN tambouren BIT(1) NOT NULL DEFAULT 0;
ALTER TABLE verein
    MODIFY COLUMN perkussionsensemble BIT(1) NOT NULL DEFAULT 0;
